---
- hosts: monitoring
  sudo: no
  gather_facts: no # disabled so dependencies role below has a chance to install python
  vars_files:
    - vars/public.yml
    - vars/private.yml
  roles:
    - {role: dependencies, tags: dependencies}
    - {role: pip, tags: pip}
    - {role: ruby, tags: ruby}
    - {role: ufw, tags: ufw}
    - {role: postfix, tags: postfix}
    - {role: apache2, tags: apache2}
    - {role: nagios, tags: nagios}
    - {role: provision, tags: provision}
