- name: pip
  src: bobbyrenwick.pip

- name: nagios
  src: netlore.nagios

- name: ufw
  src: kbrebanov.ufw

- name: apache2
  #src: PeterMosmans.apache2
  src: https://github.com/insanity54/ansible-role-apache2
  # ^-- my fix for Ubuntu 14.04 using apache2.4 with /etc/apache2/conf-available
  #     instead of /etc/apache2/conf.d

- name: postfix
  #src: tersmitten.postfix
  src: https://github.com/insanity54/ansible-postfix
  # ^-- my fix for ansible raw variable deprecation

