---

- name: delete icinga2 docker container
  tags: docker,debug
  docker:
    name: icinga2
    image: jordan/icinga2:latest
    state: absent


- name: run icinga2 docker image
  tags: docker,debug
  docker:
    name: icinga2
    image: jordan/icinga2:latest
    state: restarted
    pull: missing
    ports:
    - "80:80"
    env:
        ICINGA_PASSWORD: "{{ icinga_password }}"
        ICINGA_WEB_PASSWORD: "{{ icinga_web_password }}"
        ICINGAWEB2_PASSWORD: "{{ icinga_web_password }}"
        IDO_PASSWORD: "{{ ido_password }}"
        DEBIAN_SYS_MAINT_PASSWORD: "{{ debian_sys_maint_password }}"


# - name: debug info
#   tags: docker,debug
#   debug: msg="{{ docker_containers }}"

- name: remove any old volume links
  tags: docker
  file: path=/root/icinga2 state=absent

- name: create a link to the /etc/icinga2 docker volume
  tags: docker
  shell: ln -s $(docker inspect icinga2 | grep -B1 /etc/icinga2 | grep -o '/var/lib/docker.*_data') /root/icinga2
  args:
    creates: /root/icinga2


- name: wait for icinga2 to add config files
  tags: docker
  wait_for: path=/root/icinga2/conf.d/users.conf


- name: place custom object definitions
  tags: docker
  synchronize: src=files/conf.d/ dest=/root/icinga2/conf.d/

# debug
- name: debug
  debug: msg="System {{ inventory_hostname }} has ip {{ ansible_eth0.ipv4.address }}"

- name: compile and place host definitions
  tags: icinga2
  template: src=templates/hosts.conf.j2 dest=/root/icinga2/conf.d/hosts.conf

- name: compile and place contacts definitions
  tags: icinga2
  template: src=templates/contacts.conf.j2 dest=/root/icinga2/conf.d/contacts.conf

- name: compile and place user definitions
  tags: icinga2
  template: src=templates/users.conf.j2 dest=/root/icinag2/conf.d/users.conf
  
- name: restart docker
  tags: docker
  command: docker restart icinga2

- include: postfix.yml
