---


- name: install apt dependencies
  tags: dependencies
  apt: name={{ item.name }} state=present
  with_items:
    - name: ruby

- name: install ruby dependencies
  tags: dependencies
  gem: name={{ item.name }} state=latest
  with_items:
    - name: optiflag
    - name: hpricot


- include: postfix.yml
- include: objects.yml
- include: libexec.yml